---
name: Release
on:
  push:
    tags: ['*']

env:
  INPUT_GO_VERSION: 1.14

jobs:
  build:
    name: Build ${{ matrix.platform }}/${{ matrix.arch }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [linux, darwin, windows]
        arch: [amd64]
        include:
          - platform: linux
            arch: arm64
    steps:
      - uses: actions/setup-go@v2
      - uses: actions/checkout@v2
      - run: make release-assets
        env:
          GOOS: ${{ matrix.platform }}
          GOARCH: ${{ matrix.arch }}
      - uses: actions/upload-artifact@v2
        with:
          name: release-${{ github.sha }}
          path: '*.tgz'
      - uses: actions/upload-artifact@v2
        with:
          name: release-${{ github.sha }}
          path: '*.sha256'
  release:
    name: Release
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: release-${{ github.sha }}
      - uses: heinrichreimer/github-changelog-generator-action@v2.1.1
        id: generate_changelog
        with:
          onlyLastTag: 'true'
          stripHeaders: 'true'
          stripGeneratorNotice: 'true'
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: softprops/action-gh-release@v1
        with:
          body: ${{ steps.generate_changelog.outputs.changelog }}
          files: |
            *.gz
            *.sha256
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
