---
name: Build/Test
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  INPUT_GO_VERSION: 1.14

jobs:
  build:
    name: Build ${{ matrix.platform }}/${{ matrix.arch }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        compiler: [1.14]
    steps:
      - uses: actions/setup-go@v2
      - uses: actions/checkout@v2
      - run: make lint test build
